// Decompiled with JetBrains decompiler
// Type: RoomEditor.frmControls
// Assembly: RoomEditor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 998858C2-721B-4132-B16A-2732F6B1A670
// Assembly location: E:\ModTools\RoomEditor.exe

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace RoomEditor
{
  public class frmControls : ToolForm
  {
    private IContainer components;
    private Label label2;
    private Label label5;
    private Label label6;
    private Label label7;
    private Label label9;
    private Label label19;
    private Label label22;
    private Label label23;
    private Label label24;
    private Label label26;
    private GroupBox groupBox1;
    private Label label34;
    private Label label17;
    private Label label33;
    private Label label16;
    private Label label32;
    private Label label15;
    private Label label31;
    private Label label14;
    private Label label30;
    private Label label13;
    private GroupBox groupBox2;
    private Label label25;
    private Label label8;
    private Label label21;
    private Label label20;
    private Label label4;
    private Label label3;
    private Label label18;
    private Label label1;
    private Label label29;
    private Label label12;
    private Label label28;
    private Label label11;
    private Label label27;
    private Label label10;
    private GroupBox groupBox3;
    private GroupBox groupBox4;
    private Label label35;
    private Label label36;
    private Label label37;
    private Label label38;
    private Label label39;
    private Label label40;
    private Label label43;
    private Label label44;
    private Label label41;
    private Label label42;

    public frmControls() => this.InitializeComponent();

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.label2 = new Label();
      this.label5 = new Label();
      this.label6 = new Label();
      this.label7 = new Label();
      this.label9 = new Label();
      this.label19 = new Label();
      this.label22 = new Label();
      this.label23 = new Label();
      this.label24 = new Label();
      this.label26 = new Label();
      this.groupBox1 = new GroupBox();
      this.label34 = new Label();
      this.label17 = new Label();
      this.label33 = new Label();
      this.label16 = new Label();
      this.label32 = new Label();
      this.label15 = new Label();
      this.label31 = new Label();
      this.label14 = new Label();
      this.label30 = new Label();
      this.label13 = new Label();
      this.groupBox2 = new GroupBox();
      this.label25 = new Label();
      this.label8 = new Label();
      this.label21 = new Label();
      this.label20 = new Label();
      this.label4 = new Label();
      this.label3 = new Label();
      this.label18 = new Label();
      this.label1 = new Label();
      this.label29 = new Label();
      this.label12 = new Label();
      this.label28 = new Label();
      this.label11 = new Label();
      this.label27 = new Label();
      this.label10 = new Label();
      this.groupBox3 = new GroupBox();
      this.groupBox4 = new GroupBox();
      this.label35 = new Label();
      this.label36 = new Label();
      this.label37 = new Label();
      this.label38 = new Label();
      this.label39 = new Label();
      this.label40 = new Label();
      this.label41 = new Label();
      this.label42 = new Label();
      this.label43 = new Label();
      this.label44 = new Label();
      this.groupBox1.SuspendLayout();
      this.groupBox2.SuspendLayout();
      this.groupBox3.SuspendLayout();
      this.groupBox4.SuspendLayout();
      this.SuspendLayout();
      this.label2.AutoSize = true;
      this.label2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label2.Location = new Point(10, 21);
      this.label2.Name = "label2";
      this.label2.Size = new Size(102, 13);
      this.label2.TabIndex = 0;
      this.label2.Text = "Use current tool:";
      this.label5.AutoSize = true;
      this.label5.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label5.Location = new Point(10, 61);
      this.label5.Name = "label5";
      this.label5.Size = new Size(133, 13);
      this.label5.TabIndex = 0;
      this.label5.Text = "Cancel current action:";
      this.label6.AutoSize = true;
      this.label6.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label6.Location = new Point(10, 35);
      this.label6.Name = "label6";
      this.label6.Size = new Size(53, 13);
      this.label6.TabIndex = 0;
      this.label6.Text = "Picking:";
      this.label7.AutoSize = true;
      this.label7.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label7.Location = new Point(10, 48);
      this.label7.Name = "label7";
      this.label7.Size = new Size(51, 13);
      this.label7.TabIndex = 0;
      this.label7.Text = "Bucket:";
      this.label9.AutoSize = true;
      this.label9.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label9.Location = new Point(10, 73);
      this.label9.Name = "label9";
      this.label9.Size = new Size(99, 13);
      this.label9.TabIndex = 0;
      this.label9.Text = "Suppr selection:";
      this.label19.AutoSize = true;
      this.label19.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label19.Location = new Point(159, 21);
      this.label19.Name = "label19";
      this.label19.Size = new Size(92, 13);
      this.label19.TabIndex = 0;
      this.label19.Text = "Left mouse button";
      this.label22.AutoSize = true;
      this.label22.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label22.Location = new Point(159, 61);
      this.label22.Name = "label22";
      this.label22.Size = new Size(99, 13);
      this.label22.TabIndex = 0;
      this.label22.Text = "Right mouse button";
      this.label23.AutoSize = true;
      this.label23.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label23.Location = new Point(159, 35);
      this.label23.Name = "label23";
      this.label23.Size = new Size(47, 13);
      this.label23.TabIndex = 0;
      this.label23.Text = "Hold Ctrl";
      this.label24.AutoSize = true;
      this.label24.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label24.Location = new Point(159, 48);
      this.label24.Name = "label24";
      this.label24.Size = new Size(163, 13);
      this.label24.TabIndex = 0;
      this.label24.Text = "Hold Maj (only with suitable tools)";
      this.label26.AutoSize = true;
      this.label26.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label26.Location = new Point(159, 73);
      this.label26.Name = "label26";
      this.label26.Size = new Size(95, 13);
      this.label26.TabIndex = 0;
      this.label26.Text = "Suppr | Delete Key";
      this.groupBox1.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox1.Controls.Add((Control) this.label34);
      this.groupBox1.Controls.Add((Control) this.label17);
      this.groupBox1.Controls.Add((Control) this.label33);
      this.groupBox1.Controls.Add((Control) this.label16);
      this.groupBox1.Controls.Add((Control) this.label32);
      this.groupBox1.Controls.Add((Control) this.label15);
      this.groupBox1.Controls.Add((Control) this.label31);
      this.groupBox1.Controls.Add((Control) this.label14);
      this.groupBox1.Controls.Add((Control) this.label30);
      this.groupBox1.Controls.Add((Control) this.label13);
      this.groupBox1.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.groupBox1.Location = new Point(12, 180);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(333, 100);
      this.groupBox1.TabIndex = 1;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Windows";
      this.label34.AutoSize = true;
      this.label34.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label34.Location = new Point(159, 73);
      this.label34.Name = "label34";
      this.label34.Size = new Size(19, 13);
      this.label34.TabIndex = 1;
      this.label34.Text = "F9";
      this.label17.AutoSize = true;
      this.label17.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label17.Location = new Point(10, 73);
      this.label17.Name = "label17";
      this.label17.Size = new Size(144, 13);
      this.label17.TabIndex = 2;
      this.label17.Text = "Show marker properties:";
      this.label33.AutoSize = true;
      this.label33.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label33.Location = new Point(159, 60);
      this.label33.Name = "label33";
      this.label33.Size = new Size(19, 13);
      this.label33.TabIndex = 3;
      this.label33.Text = "F8";
      this.label16.AutoSize = true;
      this.label16.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label16.Location = new Point(10, 60);
      this.label16.Name = "label16";
      this.label16.Size = new Size(83, 13);
      this.label16.TabIndex = 4;
      this.label16.Text = "Show history:";
      this.label32.AutoSize = true;
      this.label32.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label32.Location = new Point(159, 47);
      this.label32.Name = "label32";
      this.label32.Size = new Size(19, 13);
      this.label32.TabIndex = 5;
      this.label32.Text = "F7";
      this.label15.AutoSize = true;
      this.label15.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label15.Location = new Point(10, 47);
      this.label15.Name = "label15";
      this.label15.Size = new Size(79, 13);
      this.label15.TabIndex = 6;
      this.label15.Text = "Show layers:";
      this.label31.AutoSize = true;
      this.label31.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label31.Location = new Point(159, 34);
      this.label31.Name = "label31";
      this.label31.Size = new Size(19, 13);
      this.label31.TabIndex = 7;
      this.label31.Text = "F6";
      this.label14.AutoSize = true;
      this.label14.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label14.Location = new Point(10, 34);
      this.label14.Name = "label14";
      this.label14.Size = new Size(90, 13);
      this.label14.TabIndex = 8;
      this.label14.Text = "Show preview:";
      this.label30.AutoSize = true;
      this.label30.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label30.Location = new Point(159, 21);
      this.label30.Name = "label30";
      this.label30.Size = new Size(19, 13);
      this.label30.TabIndex = 9;
      this.label30.Text = "F5";
      this.label13.AutoSize = true;
      this.label13.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label13.Location = new Point(10, 21);
      this.label13.Name = "label13";
      this.label13.Size = new Size(73, 13);
      this.label13.TabIndex = 10;
      this.label13.Text = "Show tools:";
      this.groupBox2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox2.Controls.Add((Control) this.label43);
      this.groupBox2.Controls.Add((Control) this.label44);
      this.groupBox2.Controls.Add((Control) this.label41);
      this.groupBox2.Controls.Add((Control) this.label42);
      this.groupBox2.Controls.Add((Control) this.label25);
      this.groupBox2.Controls.Add((Control) this.label8);
      this.groupBox2.Controls.Add((Control) this.label21);
      this.groupBox2.Controls.Add((Control) this.label20);
      this.groupBox2.Controls.Add((Control) this.label4);
      this.groupBox2.Controls.Add((Control) this.label3);
      this.groupBox2.Controls.Add((Control) this.label18);
      this.groupBox2.Controls.Add((Control) this.label1);
      this.groupBox2.Controls.Add((Control) this.label29);
      this.groupBox2.Controls.Add((Control) this.label26);
      this.groupBox2.Controls.Add((Control) this.label12);
      this.groupBox2.Controls.Add((Control) this.label9);
      this.groupBox2.Controls.Add((Control) this.label28);
      this.groupBox2.Controls.Add((Control) this.label11);
      this.groupBox2.Controls.Add((Control) this.label27);
      this.groupBox2.Controls.Add((Control) this.label10);
      this.groupBox2.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.groupBox2.Location = new Point(12, 12);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(333, 162);
      this.groupBox2.TabIndex = 2;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Room && Edition";
      this.label25.AutoSize = true;
      this.label25.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label25.Location = new Point(159, 139);
      this.label25.Name = "label25";
      this.label25.Size = new Size(70, 13);
      this.label25.TabIndex = 13;
      this.label25.Text = "Mouse wheel";
      this.label8.AutoSize = true;
      this.label8.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(10, 139);
      this.label8.Name = "label8";
      this.label8.Size = new Size(93, 13);
      this.label8.TabIndex = 14;
      this.label8.Text = "Zoom/Unzoom:";
      this.label21.AutoSize = true;
      this.label21.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label21.Location = new Point(159, 126);
      this.label21.Name = "label21";
      this.label21.Size = new Size(138, 13);
      this.label21.TabIndex = 9;
      this.label21.Text = "Ctrl + Y | Next mouse button";
      this.label20.AutoSize = true;
      this.label20.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label20.Location = new Point(159, 113);
      this.label20.Name = "label20";
      this.label20.Size = new Size(157, 13);
      this.label20.TabIndex = 10;
      this.label20.Text = "Ctrl + Z | Previous mouse button";
      this.label4.AutoSize = true;
      this.label4.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label4.Location = new Point(10, 126);
      this.label4.Name = "label4";
      this.label4.Size = new Size(41, 13);
      this.label4.TabIndex = 11;
      this.label4.Text = "Redo:";
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label3.Location = new Point(10, 113);
      this.label3.Name = "label3";
      this.label3.Size = new Size(41, 13);
      this.label3.TabIndex = 12;
      this.label3.Text = "Undo:";
      this.label18.AutoSize = true;
      this.label18.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label18.Location = new Point(159, 60);
      this.label18.Name = "label18";
      this.label18.Size = new Size(105, 13);
      this.label18.TabIndex = 7;
      this.label18.Text = "Middle mouse button";
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label1.Location = new Point(10, 60);
      this.label1.Name = "label1";
      this.label1.Size = new Size(73, 13);
      this.label1.TabIndex = 8;
      this.label1.Text = "Move room:";
      this.label29.AutoSize = true;
      this.label29.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label29.Location = new Point(159, 34);
      this.label29.Name = "label29";
      this.label29.Size = new Size(42, 13);
      this.label29.TabIndex = 1;
      this.label29.Text = "Ctrl + O";
      this.label12.AutoSize = true;
      this.label12.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label12.Location = new Point(10, 34);
      this.label12.Name = "label12";
      this.label12.Size = new Size(72, 13);
      this.label12.TabIndex = 2;
      this.label12.Text = "Open room:";
      this.label28.AutoSize = true;
      this.label28.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label28.Location = new Point(159, 21);
      this.label28.Name = "label28";
      this.label28.Size = new Size(42, 13);
      this.label28.TabIndex = 3;
      this.label28.Text = "Ctrl + N";
      this.label11.AutoSize = true;
      this.label11.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label11.Location = new Point(10, 21);
      this.label11.Name = "label11";
      this.label11.Size = new Size(67, 13);
      this.label11.TabIndex = 4;
      this.label11.Text = "New room:";
      this.label27.AutoSize = true;
      this.label27.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label27.Location = new Point(159, 47);
      this.label27.Name = "label27";
      this.label27.Size = new Size(42, 13);
      this.label27.TabIndex = 5;
      this.label27.Text = "Ctrl + R";
      this.label10.AutoSize = true;
      this.label10.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label10.Location = new Point(10, 47);
      this.label10.Name = "label10";
      this.label10.Size = new Size(80, 13);
      this.label10.TabIndex = 6;
      this.label10.Text = "Resize room:";
      this.groupBox3.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox3.Controls.Add((Control) this.label2);
      this.groupBox3.Controls.Add((Control) this.label19);
      this.groupBox3.Controls.Add((Control) this.label24);
      this.groupBox3.Controls.Add((Control) this.label6);
      this.groupBox3.Controls.Add((Control) this.label7);
      this.groupBox3.Controls.Add((Control) this.label23);
      this.groupBox3.Controls.Add((Control) this.label5);
      this.groupBox3.Controls.Add((Control) this.label22);
      this.groupBox3.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.groupBox3.Location = new Point(12, 286);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(333, 86);
      this.groupBox3.TabIndex = 3;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "Tools";
      this.groupBox4.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox4.Controls.Add((Control) this.label35);
      this.groupBox4.Controls.Add((Control) this.label36);
      this.groupBox4.Controls.Add((Control) this.label37);
      this.groupBox4.Controls.Add((Control) this.label38);
      this.groupBox4.Controls.Add((Control) this.label39);
      this.groupBox4.Controls.Add((Control) this.label40);
      this.groupBox4.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.groupBox4.Location = new Point(12, 378);
      this.groupBox4.Name = "groupBox4";
      this.groupBox4.Size = new Size(333, 74);
      this.groupBox4.TabIndex = 4;
      this.groupBox4.TabStop = false;
      this.groupBox4.Text = "Layers";
      this.label35.AutoSize = true;
      this.label35.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label35.Location = new Point(10, 21);
      this.label35.Name = "label35";
      this.label35.Size = new Size(128, 13);
      this.label35.TabIndex = 0;
      this.label35.Text = "Select collision layer:";
      this.label36.AutoSize = true;
      this.label36.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label36.Location = new Point(159, 21);
      this.label36.Name = "label36";
      this.label36.Size = new Size(19, 13);
      this.label36.TabIndex = 0;
      this.label36.Text = "F1";
      this.label37.AutoSize = true;
      this.label37.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label37.Location = new Point(159, 48);
      this.label37.Name = "label37";
      this.label37.Size = new Size(19, 13);
      this.label37.TabIndex = 0;
      this.label37.Text = "F3";
      this.label38.AutoSize = true;
      this.label38.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label38.Location = new Point(10, 35);
      this.label38.Name = "label38";
      this.label38.Size = new Size(102, 13);
      this.label38.TabIndex = 0;
      this.label38.Text = "Select link layer:";
      this.label39.AutoSize = true;
      this.label39.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label39.Location = new Point(10, 48);
      this.label39.Name = "label39";
      this.label39.Size = new Size(120, 13);
      this.label39.TabIndex = 0;
      this.label39.Text = "Select marker layer:";
      this.label40.AutoSize = true;
      this.label40.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label40.Location = new Point(159, 35);
      this.label40.Name = "label40";
      this.label40.Size = new Size(19, 13);
      this.label40.TabIndex = 0;
      this.label40.Text = "F2";
      this.label41.AutoSize = true;
      this.label41.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label41.Location = new Point(159, 86);
      this.label41.Name = "label41";
      this.label41.Size = new Size(41, 13);
      this.label41.TabIndex = 15;
      this.label41.Text = "Ctrl + C";
      this.label42.AutoSize = true;
      this.label42.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label42.Location = new Point(10, 86);
      this.label42.Name = "label42";
      this.label42.Size = new Size(94, 13);
      this.label42.TabIndex = 16;
      this.label42.Text = "Copy selection:";
      this.label43.AutoSize = true;
      this.label43.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label43.Location = new Point(159, 99);
      this.label43.Name = "label43";
      this.label43.Size = new Size(41, 13);
      this.label43.TabIndex = 17;
      this.label43.Text = "Ctrl + V";
      this.label44.AutoSize = true;
      this.label44.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label44.Location = new Point(10, 99);
      this.label44.Name = "label44";
      this.label44.Size = new Size(142, 13);
      this.label44.TabIndex = 18;
      this.label44.Text = "Paste as new selection:";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(357, 464);
      this.Controls.Add((Control) this.groupBox4);
      this.Controls.Add((Control) this.groupBox3);
      this.Controls.Add((Control) this.groupBox2);
      this.Controls.Add((Control) this.groupBox1);
      this.FormBorderStyle = FormBorderStyle.FixedToolWindow;
      this.Name = nameof (frmControls);
      this.StartPosition = FormStartPosition.Manual;
      this.Text = "Controls";
      this.groupBox1.ResumeLayout(false);
      this.groupBox1.PerformLayout();
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.groupBox3.ResumeLayout(false);
      this.groupBox3.PerformLayout();
      this.groupBox4.ResumeLayout(false);
      this.groupBox4.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
